name: Manual Image Build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push :
    name: Build WhoIsHomeUI Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build and Push base image
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          ECR_REPOSITORY: "who_is_home_ui"
          IMAGE_TAG: ${{ steps.date.outputs.date }}
        run: |
          docker build -t $ECR_REPOSITORY:latest  -f ./Dockerfile .
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG